#!/usr/bin/env bash
#
# Acceptance for the media pool — Phase 5a.1. Run on the VPS as root:
#
#   sudo bash scripts/verify-pool.sh
#
# Read-only with respect to real media: it seeds two throwaway 1x1 GIFs, proves
# everything against them, and archives them again on the way out. It never
# touches a curated meme.
#
# EVERY DENY CHECK HAS A POSITIVE CONTROL IN THE SAME BREATH. "GET /media/_archive/x
# returns 404" and "the entire pool is unreachable, so everything returns 404"
# produce IDENTICAL curl output. A deny assertion that is not paired with a live
# file 200ing in the same run proves precisely nothing, and would pass just as
# happily against an nginx that had lost the alias entirely.
set -uo pipefail

MINT="${MINT:-2wQq3MrFFHPQnapMt1wnZ2vGkVZDv5ENDCrdLCqFpump}"
MEDIA_ROOT="${MEDIA_ROOT:-/srv/media}"
POOL="$MEDIA_ROOT/$MINT"
HOST="${HOST:-https://1grainofrice.com}"
DAO="${DAO:-https://game.1grainofrice.com}"
BOT_USER=ricebuybot
WEB_USER=deploy

[[ $EUID -eq 0 ]] || { echo "must run as root (it tests what OTHER users can and cannot do)" >&2; exit 1; }

PASS=0; FAIL=0
ok()   { printf '  \033[32mPASS\033[0m %s\n' "$1"; PASS=$((PASS+1)); }
bad()  { printf '  \033[31mFAIL\033[0m %s\n' "$1"; FAIL=$((FAIL+1)); }
step() { printf '\n\033[1m== %s\033[0m\n' "$1"; }

# A 1x1 GIF and a 1x1 PNG. Real files: ffprobe has to be able to parse them.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
base64 -d > "$TMP/one.gif" <<< 'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'
base64 -d > "$TMP/two.png" <<< 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='
GIF_SHA="$(sha256sum "$TMP/one.gif" | cut -d' ' -f1)"
PNG_SHA="$(sha256sum "$TMP/two.png" | cut -d' ' -f1)"

manifest_sha() { sha256sum "$POOL/manifest.json" 2>/dev/null | cut -d' ' -f1; }
gen() { sudo -u "$BOT_USER" /usr/bin/node /opt/ricebuybot-media/scripts/build-manifest.ts --root "$MEDIA_ROOT" --mint "$MINT" "$@"; }

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(dirname "$HERE")"

# ---------------------------------------------------------------------------
step "preconditions: is the DEPLOYED tooling the tooling in this checkout?"

# This check exists because its absence cost a full debugging cycle. A stale copy
# in /opt reports the OLD code's behaviour, which reads exactly like a bug in the
# NEW code — you go and debug source that is not the source that ran. Never again:
# if they differ, say so before running a single assertion against them.
for f in scripts/build-manifest.ts scripts/tier.ts src/media/pool.ts src/core/tiers.ts; do
  if cmp -s "$REPO/$f" "/opt/ricebuybot-media/$f"; then
    ok "/opt/ricebuybot-media/$f matches $f"
  else
    bad "STALE: /opt/ricebuybot-media/$f differs from $f — run setup-media-pool.sh FIRST. Every result below describes the OLD code."
  fi
done

# ---------------------------------------------------------------------------
step "filesystem permissions (the fence is the filesystem, not the convention)"

# NOTE: the earlier run of this check used a literal <mint> and bash ate the
# angle brackets as a redirect, so it proved nothing. Hence $MINT, quoted.
if sudo -u "$WEB_USER" touch "$POOL/regular/x" 2>/dev/null; then
  bad "$WEB_USER CAN write to the pool — it must not"
  rm -f "$POOL/regular/x"
else
  ok "$WEB_USER (runs both websites) cannot write to the pool"
fi

if sudo -u "$BOT_USER" touch "$POOL/regular/x" 2>/dev/null; then
  ok "$BOT_USER (the curator) can write to the pool"
  sudo -u "$BOT_USER" rm -f "$POOL/regular/x"
else
  bad "$BOT_USER CANNOT write to the pool — it is the curator, it must"
fi

if sudo -u "$WEB_USER" cat "$POOL/manifest.json" >/dev/null 2>&1; then
  bad "$WEB_USER can read the pool directly — it should reach it over HTTP only"
else
  ok "$WEB_USER cannot even read the pool from disk"
fi

# ---------------------------------------------------------------------------
step "tier CLI: moves, content-addresses, regenerates — in one command"

cp "$TMP/one.gif" "$MEDIA_ROOT/_incoming/$MINT/banger.gif"
cp "$TMP/two.png" "$MEDIA_ROOT/_incoming/$MINT/doomed.png"
chown "$BOT_USER":"$BOT_USER" "$MEDIA_ROOT/_incoming/$MINT/banger.gif" "$MEDIA_ROOT/_incoming/$MINT/doomed.png"

rice-tier massive banger.gif >/dev/null 2>&1
rice-tier regular doomed.png >/dev/null 2>&1

[[ -f "$POOL/massive/$GIF_SHA.gif" ]] &&
  ok "banger.gif landed as massive/$GIF_SHA.gif (renamed to its hash)" ||
  bad "banger.gif is not at massive/$GIF_SHA.gif"

[[ -f "$POOL/massive/banger.gif" ]] &&
  bad "the ORIGINAL filename is still in the pool — a mutable URL under an immutable cache" ||
  ok "the original filename is gone: the URL is the hash, and only the hash"

if grep -q "\"$GIF_SHA\"" "$POOL/manifest.json" && grep -q '"label": "banger.gif"' "$POOL/manifest.json"; then
  ok "manifest regenerated by the same command, with sha256 + tier + human label"
else
  bad "manifest did not pick up the new meme"
fi

python3 - "$POOL/manifest.json" "$GIF_SHA" <<'PY' && ok "manifest item: tier=massive, kind=animation, rel_path is the hash" || bad "manifest item is wrong"
import json, sys
m = json.load(open(sys.argv[1]))
i = next(x for x in m["items"] if x["sha256"] == sys.argv[2])
assert i["tier"] == "massive", i
assert i["kind"] == "animation", i
assert i["rel_path"].endswith(f'massive/{sys.argv[2]}.gif'), i
PY

# ---------------------------------------------------------------------------
step "nginx: split cache policy, deny blocks, POSITIVE CONTROLS"

hdr() { curl -sS -o /dev/null -D - -m 20 "$1" 2>/dev/null | tr -d '\r'; }
code() { curl -sS -o /dev/null -w '%{http_code}' -m 20 "$1" 2>/dev/null; }

MEDIA_URL="$HOST/media/massive/$GIF_SHA.gif"
MANI_URL="$HOST/media/manifest.json"

# --- POSITIVE CONTROL. Everything below is meaningless without this line. ---
[[ "$(code "$MEDIA_URL")" == 200 ]] &&
  ok "POSITIVE CONTROL: a real meme in a tier folder serves 200 (the pool IS reachable)" ||
  bad "POSITIVE CONTROL FAILED: the pool is not serving — every 404 below is a false pass"

hdr "$MEDIA_URL" | grep -qi 'cache-control: public, max-age=31536000, immutable' &&
  ok "media file: immutable, max-age=1y (safe: the filename is the content hash)" ||
  bad "media file: wrong Cache-Control ($(hdr "$MEDIA_URL" | grep -i cache-control))"

[[ "$(code "$MANI_URL")" == 200 ]] &&
  ok "manifest: 200" || bad "manifest: not 200"

hdr "$MANI_URL" | grep -qi 'cache-control: no-cache' &&
  ok "manifest: no-cache (the mutable index revalidates; a new meme shows up at once)" ||
  bad "manifest: wrong Cache-Control ($(hdr "$MANI_URL" | grep -i cache-control))"

ETAG="$(hdr "$MANI_URL" | grep -i '^etag:' | cut -d' ' -f2)"
if [[ -n "$ETAG" ]]; then
  REVAL="$(curl -sS -o /dev/null -w '%{http_code}' -m 20 -H "If-None-Match: $ETAG" "$MANI_URL")"
  [[ "$REVAL" == 304 ]] &&
    ok "manifest: revalidates to 304 — no-cache costs a round trip, not a body" ||
    bad "manifest: If-None-Match returned $REVAL, expected 304"
else
  bad "manifest: no ETag, so no-cache means a full re-download every time"
fi

# --- the deny blocks, each against a file that DEMONSTRABLY EXISTS ---
rice-tier archive "$PNG_SHA.png" >/dev/null 2>&1
[[ -f "$POOL/_archive/$PNG_SHA.png" ]] &&
  ok "archive: the bytes are still on disk (never unlinked)" ||
  bad "archive: the file is gone from _archive"

# The file exists on disk, one directory over from a file we just proved 200s.
# A 404 here is therefore the deny rule firing, not the pool being broken.
[[ "$(code "$HOST/media/_archive/$PNG_SHA.png")" == 404 ]] &&
  ok "_archive/<real file>: 404 (exists on disk, denied over HTTP)" ||
  bad "_archive is SERVED — a retired meme is still public"

hdr "$HOST/media/_archive/$PNG_SHA.png" | grep -qi 'cache-control: no-store' &&
  ok "the deny 404 is no-store (not cached for a year on a path that may exist later)" ||
  bad "the deny 404 inherits a cacheable header"

[[ "$(code "$HOST/media/_incoming/x.gif")" == 404 ]] &&
  ok "_incoming: 404" || bad "_incoming is reachable"

[[ "$(code "$HOST/media/")" == 404 || "$(code "$HOST/media/")" == 403 ]] &&
  ok "no directory listing" || bad "directory listing is on ($(code "$HOST/media/"))"

grep -q '"'"$PNG_SHA"'"' "$POOL/manifest.json" &&
  bad "the archived meme is still in the manifest" ||
  ok "the archived meme is out of the manifest (out of rotation, still recoverable)"

# ---------------------------------------------------------------------------
step "the generator ERRORS instead of silently ignoring"

BEFORE="$(manifest_sha)"

mkdir -p "$POOL/epic"; chown "$BOT_USER":www-data "$POOL/epic"
if gen >/dev/null 2>&1; then bad "stray folder epic/ was IGNORED"; else ok "stray folder epic/ -> generator errors"; fi
[[ "$(manifest_sha)" == "$BEFORE" ]] &&
  ok "  ...and the previous manifest is INTACT (a bad pool does not destroy a good manifest)" ||
  bad "  ...but the manifest was clobbered"
rmdir "$POOL/epic"

mkdir -p "$POOL/massive/best"; chown "$BOT_USER":www-data "$POOL/massive/best"
if gen >/dev/null 2>&1; then bad "nested folder massive/best/ was IGNORED"; else ok "nested folder massive/best/ -> generator errors"; fi
rmdir "$POOL/massive/best"

# Same bytes, two tiers. Only reachable by editing the pool by hand — tier.ts
# refuses to create it, which is the next check.
sudo -u "$BOT_USER" cp "$POOL/massive/$GIF_SHA.gif" "$POOL/whale/$GIF_SHA.gif"
DUP="$(gen 2>&1)"
if [[ $? -eq 0 ]]; then
  bad "the same meme in two tiers was accepted"
else
  grep -q 'same content is in two tiers' <<< "$DUP" && grep -q massive <<< "$DUP" && grep -q whale <<< "$DUP" &&
    ok "same sha256 in two tiers -> HARD ERROR naming BOTH paths" ||
    bad "duplicate errored, but did not name both paths: $DUP"
fi
[[ "$(manifest_sha)" == "$BEFORE" ]] &&
  ok "  ...and the previous manifest is INTACT" ||
  bad "  ...but the manifest was clobbered"
sudo -u "$BOT_USER" rm -f "$POOL/whale/$GIF_SHA.gif"

# tier.ts must refuse to create the situation in the first place.
cp "$TMP/one.gif" "$MEDIA_ROOT/_incoming/$MINT/same-meme-new-name.gif"
chown "$BOT_USER":"$BOT_USER" "$MEDIA_ROOT/_incoming/$MINT/same-meme-new-name.gif"
# CAPTURE, then grep — do NOT pipe rice-tier into grep here.
#
# This script runs under `set -o pipefail`, and rice-tier is SUPPOSED to exit 1 in
# this check: it is refusing, which is the behaviour under test. Under pipefail the
# pipeline takes the rightmost NON-ZERO status, so `rice-tier … | grep -q …` reports
# rice-tier's 1 even when grep matched perfectly — and the check reads as "tier.ts
# allowed the duplicate" while tier.ts was doing exactly the right thing.
#
# A false FAIL on the one assertion whose command is expected to fail. Assert on the
# OUTPUT and the EXIT CODE separately, so neither can be mistaken for the other.
REFUSAL="$(rice-tier whale same-meme-new-name.gif 2>&1)"
REFUSAL_CODE=$?
if [[ $REFUSAL_CODE -ne 0 ]] && grep -qi 'already in the pool, in a DIFFERENT tier' <<< "$REFUSAL"; then
  ok "tier.ts REFUSES to put the same bytes in a second tier (exit $REFUSAL_CODE)"
else
  bad "tier.ts allowed the same meme into two tiers (exit $REFUSAL_CODE): $REFUSAL"
fi

# The refusal must also NAME the tier it is already in — that is what Phase 8.5's DM
# flow turns into "already in Massive — move it to Whale?".
grep -qi 'tier: massive' <<< "$REFUSAL" &&
  ok "  ...and names the tier it is already in" ||
  bad "  ...but does not say which tier it is in"

[[ ! -f "$POOL/whale/$GIF_SHA.gif" ]] &&
  ok "  ...and did NOT move the file (the refusal actually refused)" ||
  bad "  ...but moved the file anyway"

# A refusal that cannot be overridden is a wall, not a policy — and the tool used to
# SUGGEST a relocation command that collided the file with itself and failed. Prove
# the escape hatch works, and that it leaves exactly ONE copy behind.
rice-tier whale "$GIF_SHA.gif" --move >/dev/null 2>&1
if [[ -f "$POOL/whale/$GIF_SHA.gif" && ! -f "$POOL/massive/$GIF_SHA.gif" ]]; then
  ok "--move re-tiers it (massive -> whale) and leaves ONE copy"
else
  bad "--move did not relocate the meme"
fi
# Put it back where the rest of the script expects it.
rice-tier massive "$GIF_SHA.gif" --move >/dev/null 2>&1
[[ -f "$POOL/massive/$GIF_SHA.gif" && ! -f "$POOL/whale/$GIF_SHA.gif" ]] &&
  ok "--move back again (whale -> massive)" ||
  bad "--move could not move it back"

sudo -u "$BOT_USER" rm -f "$MEDIA_ROOT/_incoming/$MINT/same-meme-new-name.gif"

# ---------------------------------------------------------------------------
step "the websites are untouched"

for u in "$HOST/" "$DAO/RiceDAO/"; do
  c="$(curl -sSL -o /dev/null -w '%{http_code}' -m 25 "$u")"
  [[ "$c" == 200 ]] && ok "$u -> 200" || bad "$u -> $c"
done

# ---------------------------------------------------------------------------
step "cleanup: leave the pool exactly as we found it"

sudo -u "$BOT_USER" rm -f "$POOL/massive/$GIF_SHA.gif" "$POOL/_archive/$PNG_SHA.png"
gen >/dev/null 2>&1
echo "  test media removed; manifest regenerated ($(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["count"])' "$POOL/manifest.json") items)"

# ---------------------------------------------------------------------------
printf '\n\033[1m%d passed, %d failed\033[0m\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]] || exit 1
